Feat/student list
bvolcan/ds-front pull request #5
Opened 2023-04-11 18:54 UTC by LeonardoGuths

1 migalha de aprovaçao?

2023-04-13 14:51 UTC, bvolcan commented
Ainda tá faltando tirar aquele comportamento de poder selecionar cada linha da tabela, certo?

2023-04-13 16:58 UTC, LeonardoGuths commented
> Ainda tá faltando tirar aquele comportamento de poder selecionar cada linha da tabela, certo?

sim, ainda tem uns detalhezinhos pra finalizar, ainda tem que sincronizar com o back tb etc

2023-04-26 18:55 UTC, bvolcan requested changes
Um bocado de alterações hein. Acabei sendo chato dnv, foi mal.
Qualquer coisa chama.

2023-04-26 18:55 UTC, bvolcan commented on src/components/AdvisorClassTable/index.js
> +	console.log(rows)
Console.log

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +	console.log(rows)
console.log

2023-04-26 18:55 UTC, bvolcan commented on src/containers/Student/List/index.js
> +				console.log(data)
console.log

2023-04-26 18:55 UTC, bvolcan commented on src/components/UploadButton/index.js
Não que precise fazer algo sobre isso por enquanto, mas esse botão no fim n vai ser usado pra nada, pelo menos não com essa funcionalidade de upar um pdf.

2023-04-26 18:55 UTC, bvolcan commented on src/components/ShowRevision/ShowRevision.js
Comentado no outro PR.

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +import FilterListIcon from '@mui/icons-material/FilterList'
Todos esses imports que tu tá fazendo que são de um mesmo lugar, como "@mui/material/{componente}" podem ser importados desestruturando, assim: `import { Box, Table, TableBody} from '@mui/material`
Acredito que possa deixar o código mais limpo.

Provavelmente tem alguns outros casos desse em outros arquivos que eu não comentei.

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +}
Algum motivo específico pra não usar arrow function nessas funções?

2023-04-26 18:55 UTC, bvolcan commented on src/components/AdvisorClassTable/index.js
Vi que nesse componente foram usados vários "React.{alguma coisa}", recomendo fazer a importação individual de cada um deles, até pra sabermos o que tá sendo usado do react e também pra deixar o código mais legivel. Algo como `import React, { useState, useCallback } from 'react'`

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +	let id = data.id
Aqui não poderiam ser usado "const" ao invés de "let"?

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +						// sx={{ pl: 4 }}
É algo importante de ser deixado comentado aqui?

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +		} else if (selectedIndex > 0) {
Esse if é necessário? Se não entrar em nenhum dos ifs anteriores, tem algum outro caso além do desse if dessa linha?

2023-04-26 18:55 UTC, bvolcan commented on src/components/EnhancedTable/index.js
> +												// sx={{ pl: 4 }}
Mais um comentário a princípio sem utilidade aqui.

2023-04-26 18:55 UTC, bvolcan commented on src/containers/Advisor/ViewClass/index.js
> +let turma = 'TCC1 2022/2'
Com a integração, ainda tem a necessidade de ter esses lets?

2023-04-26 18:55 UTC, bvolcan commented on src/containers/Advisor/ViewClass/index.js
Isso não teria que ficar em outra branch depois?

2023-04-26 18:55 UTC, bvolcan commented on src/containers/Advisor/ViewClass/style.css
Mesma coisa de ser em outra branch.

2023-04-26 18:55 UTC, bvolcan commented on src/routes.js
> +				<Route component={ViewClass} path='/advisorviewclass' />
Mesma coisa de ser em outra branch.

2023-04-26 18:55 UTC, bvolcan commented on src/routes.js
> +				<Route component={ViewRevision} path='/viewrevision' />
Já nem sei mais se essa parte eu comentei em outro PR kkkk, mas só pra assegurar, vamos manter o padrão dos URLs do em português já que é algo que o usuário final vai ter contato direto.

2023-04-26 18:55 UTC, bvolcan commented on src/containers/Student/List/index.js
Já foi comentado em outro PR, mas tanto o container "List" quanto o "ViewRevision" podem ficar direto na pasta "container" já que são rotas/telas separadas uma da outra.

2023-04-26 18:55 UTC, bvolcan commented on src/components/AdvisorClassTable/style.css
É intencional? uhasuasuhasuhuhasusha

2023-05-08 00:34 UTC, merged