refac: ChangePassword container moved out from the Login folder
bvolcan/ds-front pull request #7
Opened 2023-04-17 18:47 UTC by LeonardoGuths

2023-04-17 18:59 UTC, bvolcan requested changes
Já aproveita e adicionada um alt no img logo usado no header pra tirar a warning. Arquivo containers/ChangePassword, linha 8, só colocar a tag assim: `<img src={Logo} alt='Logo'></img>`

2023-04-26 05:39 UTC, LeonardoGuths commented
@bvolcan oi

2023-04-26 17:29 UTC, bvolcan commented
Precisa resolver os conflitos ainda

2023-04-26 17:34 UTC, LeonardoGuths commented
> Precisa resolver os conflitos ainda

resolvido meu querido.

2023-04-26 18:22 UTC, bvolcan commented on src/containers/ChangePassword/index.js
> -			<Header></Header>
É intencional essa tela ter ficado sem nenhum header?

2023-04-26 18:44 UTC, LeonardoGuths commented on src/containers/ChangePassword/index.js
> -			<Header></Header>
ta ai um bom ponto

2023-04-26 19:05 UTC, bvolcan commented on src/containers/ChangePassword/index.js
> -			<Header></Header>
Talvez entraria o caso de ser o header sem o icone de usuário lá né, mas como essa tela provavelmente n vai ser usada no projeto, não agora pelo menos, acho q da pra deixar esse PR parado por agr

2023-04-26 22:25 UTC, LeonardoGuths commented on src/containers/ChangePassword/index.js
> -			<Header></Header>
sim sim, acho q é a boa

2023-05-08 00:34 UTC, merged