Feat/student view revision
bvolcan/ds-front pull request #9
Opened 2023-04-23 15:50 UTC by LeonardoGuths

view revisions page, fully integrated with the json pattern coming from the request. still need the request. missing back-front integration.

2023-04-23 17:31 UTC, LeonardoGuths commented
solved conflict on components index file

2023-04-26 17:30 UTC, bvolcan commented
Aqui também tem conflitos que precisam ser resolvidos

2023-04-26 17:46 UTC, LeonardoGuths commented
> Aqui também tem conflitos que precisam ser resolvidos

resolvido também meu querido.

2023-04-26 18:19 UTC, bvolcan requested changes
Não queria mas acabei sendo meio chato, foi mal huasuhasuhas. 
A princípio as coisas que eu acho mais importante de serem mudadas são rápidas de fazer até a demo. Qualquer coisa responde aqui ou me chama q a gente troca uma ideia.

2023-04-26 18:19 UTC, bvolcan commented on src/containers/Student/ViewRevision/index.js
Acredito que não tem necessidade de o "ViewRevision" ficar dentro de uma pasta "Student". Pode deixar direto na pasta "containers"

2023-04-26 18:19 UTC, bvolcan commented on src/routes.js
> +				<Route component={ViewRevision} path='/viewrevision' />
Vamos manter o padrão das rotas no front em português já que vai ser algo que os usuários finais vão estar em contato direto.

2023-04-26 18:50 UTC, LeonardoGuths commented on src/components/ShowRevision/ShowRevision.js
> +	// console.log(data)
resolvido

2023-04-26 18:50 UTC, LeonardoGuths commented on src/containers/Student/ViewRevision/index.js
resolvido

2023-04-26 18:50 UTC, LeonardoGuths commented on src/routes.js
> +				<Route component={ViewRevision} path='/viewrevision' />
resolvido

2023-04-26 18:54 UTC, LeonardoGuths commented on src/components/ShowRevision/ShowRevision.js
> +const ShowRevision = ({ isRevision, data }) => {
1. po n sei outro nome pra botar 
2. resolvido
3. entendi porém deixarei pra depois

2023-04-26 19:04 UTC, bvolcan requested changes
Antes de eu conseguir ver direitinho as coisas que foram alteradas depois dos meus comentários, te peço pra cuidar os merges que tu tá fazendo pq tá vindo coisa duplicada e coisas que foram comentadas em outros PRs.
Seguindo nesse problema, eu notei que ao tentar resolver o lance de tirar um dos containers de dentro da pasta "Student", com o merge acabou ficando dois "ViewRevision" no código.
Se tu puder desfazer esse último commit e tentar pelo menos separar em dois commits o merge e as alterações que tu fez a partir dos meus comentários eu agradeço.

2023-04-26 20:19 UTC, LeonardoGuths commented
> Antes de eu conseguir ver direitinho as coisas que foram alteradas depois dos meus comentários, te peço pra cuidar os merges que tu tá fazendo pq tá vindo coisa duplicada e coisas que foram comentadas em outros PRs. Seguindo nesse problema, eu notei que ao tentar resolver o lance de tirar um dos containers de dentro da pasta "Student", com o merge acabou ficando dois "ViewRevision" no código. Se tu puder desfazer esse último commit e tentar pelo menos separar em dois commits o merge e as alterações que tu fez a partir dos meus comentários eu agradeço.

defazer o ultimo commit é PUTARIA ta

2023-05-08 00:34 UTC, merged